
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Provider from '../utils/providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useRouter } from 'next/navigation';
import Layout from './MainLayot';

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Mweto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className='w-screen h-[90vh]'>
      <Layout>
        {children}
      </Layout>
        
       
      </body>
    </html>
  );
}
